#!/bin/bash

set -eu

# Copyright (c) 2020 Ionic Security
# Author: Ionic Security dev@ionicsecurity.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

[ $# -eq 1 ] && [ "${1:-}" = "--summary" ] && exit 2

if [ -t 0 ] ; then
    echo >&2
    echo 'Usage: clevis decrypt ionic < JWE > PLAINTEXT' >&2
    echo >&2
    exit 1
fi

read -r -d . hdr64
if ! hdr="$(jose fmt --quote="$hdr64" --string --b64load --object --output=-)" ; then
    echo 'JWE header corrupt' >&2
    exit 1
fi

if [ "$(jose fmt --json="$hdr" --get clevis --get pin --unquote=-)" != ionic ] ; then
    echo 'JWE pin mismatch!' >&2
    exit 1
fi

if ! keyid="$(jose fmt --json="$hdr" --get clevis --get ionic --get keyid --unquote=-)" ; then
    echo 'JWE missing 'clevis.ionic.keyid' header parameter!' >&2
    exit 1
fi
if ! generaloptions="$(jose fmt --json="$hdr" --get clevis --get ionic --get generaloptions --unquote=-)" ; then
    echo 'JWE missing 'clevis.ionic.generaloptions' header parameter!' >&2
    exit 1
fi

# fetch the created Ionic Key and extract its base64 encoded key bytes
kf="machina $generaloptions key fetch -i $keyid -s"
key64=$(eval "${kf}" | awk '/keyData/{gsub(/[",]/,"",$3);print $3}')
# convert from base64 to base64url encoding
key64=${key64%=}
key64=${key64//+/-}
key64=${key64//\//_}
# assemble the jwk
jwk="$(jose jwk gen -i '{"alg":"A256GCM"}' | jose fmt -j- -O -q $key64 -Ss k -Uo-)"

# perform decryption
exec jose jwe dec -k- -i- < <(echo -n "$jwk$hdr64."; /bin/cat)
