CLEVIS-ENCRYPT-IONIC(1)
=======================
:doctype: manpage


== NAME

clevis-encrypt-ionic - Encrypts using an ionic policy

== SYNOPSIS

*clevis encrypt ionic* CONFIG < PT > JWE

== OVERVIEW

The *clevis encrypt ionic* command encrypts using an ionic policy.
Its only argument is the JSON configuration object.

#%# And so on ...

Encrypting data using the ionic pin works like this:

    $ clevis encrypt ionic '{"@mand1@":"@@","@mand2":"@@"}' < PT > JWE

To decrypt the data, just pass it to the *clevis decrypt* command:

    $ clevis decrypt < JWE > PT

== CONFIG

This command uses the following configuration properties:

#%# Keep this in sync with the short help in clevis-encrypt-@pin@

* *@mand1@* (string) :
  @@ (REQUIRED)

* *@mand2@* (string) :
  @@ (REQUIRED)

* *@opt1@* (string) :
  @@ (default: @@)

== BUGS

In virtual machine environments the machina cli may throw a <errno> error if there is insufficient entropy. This can be remedied with the haveged tool (see: <dev page on haveged>). 

== SEE ALSO

link:clevis-decrypt.1.adoc[*clevis-decrypt*(1)]
